steps:
  # Creates the production .env file
  - name: "alpine"
    entrypoint: sh
    args: ["-c", "printenv > packages/backend/.env"]
    env:
      - API_KEY=$_API_KEY
      - RPC_URL=$_RPC_URL
      - OP_RPC_URL=$_OP_RPC_URL
      - ENCRYPTION_KEY=$_ENCRYPTION_KEY
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd packages/backend
        gcloud app deploy --no-cache --quiet
timeout: "1600s"
